apiVersion: v1
kind: Service
metadata:
  name: developer-service
spec:
  selector:
    app: developer
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developer-deployment
spec:
  spec:
  selector:
    matchLabels:
      app: developer
  replicas: 1
  template:
    metadata:
      labels:
        app: developer
    spec:
      containers:
      - name: developer-con
        image: gautammandlik/developer:latest
        ports:
        - containerPort: 8080
