apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devops-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /devops
          backend:
            serviceName: devops-service
            servicePort: 8081
        - path: /devops
          backend:
            serviceName: devops-service
            servicePort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: devops-service
  labels:
    app: devops
spec:
  type: NodePort
  selector:
    app: devops
  ports:
  - protocol: TCP
    port: 8081
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-deployment
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 1
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops-con
        image: gautammandlik/devops:latest
        ports:
        - containerPort: 8081

