apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules: 
  - http:
      paths:
      - path: /developer
        backend:
          serviceName: developer-service
          servicePort: 8080
      - path: /devops
        backend:
          serviceName: devops-service
          servicePort: 8081
      - path: /it
        backend:
          serviceName: it-service
          servicePort: 8082
              