apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules: 
  - http:
      paths:
      - path: /it
        pathType: Prefix
        backend:
          service:
            name: it-service
            port:
              number: 8082
      - path: /devops
        pathType: Prefix
        backend:
          service:
            name: devops-service
            port:
              number: 8081
      - path: /developer
        pathType: Prefix
        backend:
          service:
            name: developer-service
            port:
              number: 8080                                    