---
apiVersion: v1
kind: Service
metadata:
  name: it-service
  labels:
    app: it
spec:
  type: NodePort
  selector:
    app: it
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-deployment
spec:
  selector:
    matchLabels:
      app: it
  replicas: 1
  template:
    metadata:
      labels:
        app: it
    spec:
      containers:
      - name: it-con
        image: gautammandlik/it:tagname:latest
        ports:
        - containerPort: 8082


